config/routes.rb
Rails.application.routes.draw do

  mount Knock::Engine => "/knock"

  resources :scores
  resources :alerts
  resources :paths
  resources :lines
  resources :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  post 'facebook/callback'=> 'users#facebook'
  post 'user/login'=> 'users#login'

  root 'home#index'

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do

      resource :country do
        get 'find/:letters', controller: 'country', action: :find_match
        post 'create', controller: 'country', action: :create
      end

      resource :state do
        get 'find/:country_id/:letters', controller: 'state', action: :find_match
        post 'create', controller: 'state', action: :create
      end

      resource :city do
        get 'find/:state_id/:letters', controller: 'city', action: :find_match
        post 'create', controller: 'city', action: :create
      end

      resource :line_search do
        get 'search/:country/:state/:city', controller: 'line_search', action: :search_lines
        get 'lines/:line_id', controller: 'line_search', action: :line_instances
      end

      resource :user do
        post 'location/push/sensor', controller: 'user', action: :location_push
        get 'location/retrieve/sensor', controller: 'user', action: :location_retrieve
      end

    end
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/alert.rb
class Alert < ActiveRecord::Base
  belongs_to :user
  belongs_to :line

  validates :user_id, :line_id, :position, :range, :active, presence: true, allow_blank: false
end

app/models/city.rb
class City < ActiveRecord::Base

  validates :name, uniqueness: true, presence: true, allow_blank: false
  validates :state_id, presence: true, allow_blank: false

  belongs_to :state
  has_many :lines


end

app/models/country.rb
class Country < ActiveRecord::Base

  validates :name, uniqueness: true, presence: true, allow_blank: false

  has_many :states

end

app/models/facebook.rb
class Facebook

  def self.authenticate(token)
    begin
      graph = Koala::Facebook::API.new(token)
      user_info = graph.get_object("me")
      random_password = Digest::SHA1.hexdigest([Time.now, rand].join) #pog from hell
      return {name: user_info['name'], email: user_info['email'], facebook_id: user_info['id'], :password=> random_password, :password_confirmation => random_password}
    rescue Koala::Facebook::AuthenticationError => e
      raise Exception.new(e.message)
    end
  end

end

app/models/line.rb
class Line < ActiveRecord::Base

  include LineInstance

  validates :name, uniqueness: true, presence: true, allow_blank: false
  validates :city_id, presence: true, allow_blank: false


  has_one :path
  belongs_to :city
end

app/models/line_route_log.rb
class LineRouteLog < ActiveRecord::Base
  belongs_to :user
  belongs_to :line

  include LineInstanceRouteLog

  def readonly?
    true
  end

end

app/models/path.rb
class Path < ActiveRecord::Base
  belongs_to :line

  validates :line, :line_id, presence: true, allow_blank: false, uniqueness: true
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :user

  validates :user, :user_id, presence: true, allow_blank: false
  validates_uniqueness_of :user, :user_id

  before_save :add_hit

  def add_hit
    self.hits = self.hits.to_i + 1
    self.last_hit = Time.now
  end

end

app/models/state.rb
class State < ActiveRecord::Base

  validates :name, uniqueness: true, presence: true, allow_blank: false
  validates :uf, uniqueness: true, presence: true, allow_blank: false
  validates :country_id, presence: true, allow_blank: false

  belongs_to :country
  has_many :cities
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :email, :password, :password_confirmation, presence: true, if: "facebook_id.blank? || facebook_id.nil?"
  validates :email, uniqueness: true, if: "facebook_id.blank? || facebook_id.nil?"
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }, if: "facebook_id.blank? || facebook_id.nil?"

  has_secure_password

  has_one :score
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index 
  end

end

app/controllers/paths_controller.rb
class PathsController < ApplicationController
  include RestApiConcerns
  before_action :authenticate, if: "Rails.env.production? || Rails.env.development?"
  before_action :set_path, only: [:show, :edit, :update, :destroy]

  # GET /paths
  # GET /paths.json
  def index
    limit = params[:limit]||10
    offset = params[:offset]||0
    paths = Path.limit(limit).offset(offset)
    render json: paths, status: :ok
  end

  # GET /paths/1
  # GET /paths/1.json
  def show
    render json: @path,  status: :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_path
      @path = Path.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def path_params
      params.require(:path).permit(:line_id, :data)
    end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/country_helper.rb
module CountryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/helpers/paths_helper.rb
module PathsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/state_helper.rb
module StateHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/paths/_form.html.erb
<%= form_for(@path) do |f| %>
  <% if @path.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@path.errors.count, "error") %> prohibited this path from being saved:</h2>

      <ul>
      <% @path.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :line_id %><br>
    <%= f.text_field :line_id %>
  </div>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.text_area :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paths/edit.html.erb
<h1>Editing Path</h1>

<%= render 'form' %>

<%= link_to 'Show', @path %> |
<%= link_to 'Back', paths_path %>

app/views/paths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Paths</h1>

<table>
  <thead>
    <tr>
      <th>Line</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paths.each do |path| %>
      <tr>
        <td><%= path.line %></td>
        <td><%= path.data %></td>
        <td><%= link_to 'Show', path %></td>
        <td><%= link_to 'Edit', edit_path_path(path) %></td>
        <td><%= link_to 'Destroy', path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Path', new_path_path %>

app/views/paths/new.html.erb
<h1>New Path</h1>

<%= render 'form' %>

<%= link_to 'Back', paths_path %>

app/views/paths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Line:</strong>
  <%= @path.line %>
</p>

<p>
  <strong>Data:</strong>
  <%= @path.data %>
</p>

<%= link_to 'Edit', edit_path_path(@path) %> |
<%= link_to 'Back', paths_path %>